/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HarmonizacaoFacialRouteImport } from './routes/harmonizacao-facial'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HarmonizacaoFacialRoute = HarmonizacaoFacialRouteImport.update({
  id: '/harmonizacao-facial',
  path: '/harmonizacao-facial',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/harmonizacao-facial': typeof HarmonizacaoFacialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/harmonizacao-facial': typeof HarmonizacaoFacialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/harmonizacao-facial': typeof HarmonizacaoFacialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/harmonizacao-facial'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/harmonizacao-facial'
  id: '__root__' | '/' | '/harmonizacao-facial'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HarmonizacaoFacialRoute: typeof HarmonizacaoFacialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harmonizacao-facial': {
      id: '/harmonizacao-facial'
      path: '/harmonizacao-facial'
      fullPath: '/harmonizacao-facial'
      preLoaderRoute: typeof HarmonizacaoFacialRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HarmonizacaoFacialRoute: HarmonizacaoFacialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
